
version: '3'
services:
  pg: 
    image: postgres:12
    environment:
      - "POSTGRES_PASSWORD=dalong"
    ports:
    - "5432:5432"
  redis:
    image: redis
    ports:
    - "6379:6379"
  cubestorage:
    image:  cubejs/cubestore:build-100
    ports:
    - "3306:3306"
    